In [ ]:
WAP to create your own range function

In [3]:
import numpy as np

In [4]:
np.arange(11.2,2,-1.2)

array([11.2, 10. ,  8.8,  7.6,  6.4,  5.2,  4. ,  2.8])

In [ ]:
linspace

In [5]:
np.linspace(1,10,15)             #(start,end,no.s btween s and e)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [7]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.trace(a)     #sum of diagonal elements

15

In [ ]:
Array and matrix difference
    -matrix is a subclass of array
    -array can be n dimensional but matrix is always 2 dimensional
    -

In [11]:
a=np.array([[[1,2],[3,4]]])
a.ndim

3

In [12]:
a=np.mat([[[1,2],[3,4]]])
a.ndim

ValueError: matrix must be 2-dimensional

In [13]:
b=np.array([[5,6],[7,8]])

In [14]:
a*b

array([[[ 5, 12],
        [21, 32]]])

In [15]:
a1=np.mat(a)
b1=np.mat(b)

In [16]:
a1*b1

matrix([[19, 22],
        [43, 50]])

In [17]:
a**2

array([[[ 1,  4],
        [ 9, 16]]], dtype=int32)

In [18]:
a1**2

matrix([[ 7, 10],
        [15, 22]])

In [19]:
from numpy import linalg

In [20]:
a=np.array([[1,2],[3,4]])

In [21]:
v=np.linalg.inv(a)

In [22]:
v

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [23]:
np.dot(a,v)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

## Random number generation using numpy

In [24]:
from numpy import random

In [27]:
a=np.random.rand(3,3)
a

array([[0.81993613, 0.22112205, 0.32354698],
       [0.49522934, 0.81742546, 0.52672862],
       [0.47616485, 0.54624114, 0.0645169 ]])

In [26]:
a

array([[0.80911086, 0.63187596, 0.02152685],
       [0.97982313, 0.99092811, 0.91388391],
       [0.52248309, 0.43001393, 0.10037816]])

In [28]:
a=np.random.rand(4,4)

In [29]:
a

array([[0.28180687, 0.19004891, 0.61391979, 0.40994527],
       [0.46398071, 0.54914398, 0.53155701, 0.80928722],
       [0.81751049, 0.1008466 , 0.97615927, 0.01863786],
       [0.78883635, 0.67138979, 0.42028684, 0.16801986]])

In [30]:
#for array in int
a=np.random.randint(10,30,(3,3))
a

array([[16, 15, 21],
       [29, 11, 16],
       [25, 23, 26]])

In [31]:
np.random.randn(4,4)

array([[-0.60376839,  1.59002055, -0.31366377, -0.16579559],
       [-1.92162567,  1.48542007, -1.6143553 ,  0.66731843],
       [-0.6761928 , -0.73564212,  0.39190298, -0.18842631],
       [-0.1032147 ,  0.45241839, -1.49929747,  0.34603226]])

In [37]:
c=np.random.randint(10,100,(2,2))
c

array([[73, 80],
       [38, 47]])

In [33]:
c.sort()

In [38]:
c

array([[73, 80],
       [38, 47]])

In [35]:
c.sort(axis=0)

In [39]:
c

array([[73, 80],
       [38, 47]])

In [40]:
c.sort(axis=1)
c

array([[73, 80],
       [38, 47]])

In [41]:
c.max()

80

In [42]:
c.min()

38

In [45]:
np.argmax(c,axis=0)

array([0, 0], dtype=int64)

In [47]:
np.argmin(c)

2

In [48]:
np.cumsum([1,2,3,4,5,6,7,8,9])

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [49]:
np.cumsum([[1,2,3],[4,5,6]])

array([ 1,  3,  6, 10, 15, 21], dtype=int32)