## universal functions

In [1]:
import numpy as np

In [2]:
a=np.array([1,4,9,16,25,36,49,64,81,100])
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [3]:
np.sin(a)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175,
       -0.99177885, -0.95375265,  0.92002604, -0.62988799, -0.50636564])

In [4]:
np.sqrt(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
np.cos(a)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281,
       -0.12796369,  0.30059254,  0.39185723,  0.77668598,  0.86231887])

In [6]:
np.exp(a)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 1.90734657e+21, 6.23514908e+27,
       1.50609731e+35, 2.68811714e+43])

In [7]:
np.log(a)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 , 4.15888308, 4.39444915, 4.60517019])

In [8]:
from numpy import pi

In [9]:
np.sin(pi/2)

1.0

In [10]:
np.cos(pi/4)

0.7071067811865476

In [11]:
a=np.array([12.45,3.34,15.67,-9.17])          #gives lowest
np.floor(a)

array([ 12.,   3.,  15., -10.])

In [12]:
np.ceil(a)             #gives highest

array([13.,  4., 16., -9.])

## Shape manipulation:

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9])
np.reshape(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.reshape(arr,(9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [23]:
arr.resize((3,3))

In [24]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b=a.flatten()
b

array([1, 2, 3, 4, 5, 6])

## Lambda function: it is a anonymous function

In [30]:
c=lambda a,b:a+b

In [31]:
c(12,3)

15

In [35]:
d=lambda c:(9/5)*c+32

In [36]:
d(0)

32.0

In [37]:
w=lambda a,b:a**b
w(10,2)

100

In [38]:
np.fromfunction(lambda x,y:x+y,(4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [39]:
np.fromiter([1,2,3,4,5],dtype=float)

array([1., 2., 3., 4., 5.])

In [42]:
np.fromstring("1 2 3 4 5 6 7 8 9",sep=" ",dtype=int)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
Array of zeros:

In [48]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [55]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
np.diag(a,k=0)

array([1, 5, 9])

In [57]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [58]:
np.tri(3,k=1)

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [60]:
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [61]:
np.diagflat([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [64]:
np.diagflat([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [1]:
import numpy as np

In [4]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [7]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])