In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [4]:
arr[1][1]=50

In [5]:
arr

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [6]:
arr=np.array(arr,dtype=float)
arr

array([[ 1.,  2.,  3.],
       [ 4., 50.,  6.],
       [ 7.,  8.,  9.]])

In [7]:
arr=np.array([[90,86,67,55,49],[89,34,45,78,86]])
arr

array([[90, 86, 67, 55, 49],
       [89, 34, 45, 78, 86]])

In [8]:
passing_marks=50

In [9]:
arr[arr>passing_marks]

array([90, 86, 67, 55, 89, 78, 86])

In [ ]:
wap to create two arrays of distance covered by two cycles add them up to get the array of totl distance coverd if t
the distance is > 30,filter those values only

In [16]:
cycle1_dis=np.array([32,45,26])
cycle2_dis=np.array([34,36,22])
total_dis=cycle1_dis+cycle2_dis

In [17]:
total_dis

array([66, 81, 48])

In [19]:
totl_dis=50

In [20]:
total_dis[total_dis>50]

array([66, 81])

In [21]:
s=np.array([["Dehi","Mumbai","Pune","indore","chennai"],["Delhi","maha","Maha","MP","TN"]])
s

array([['Dehi', 'Mumbai', 'Pune', 'indore', 'chennai'],
       ['Delhi', 'maha', 'Maha', 'MP', 'TN']], dtype='<U7')

In [22]:
s[0:2,1:3]

array([['Mumbai', 'Pune'],
       ['maha', 'Maha']], dtype='<U7')

In [23]:
s[0:2,3:5]

array([['indore', 'chennai'],
       ['MP', 'TN']], dtype='<U7')

In [24]:
s[0:2,3:5][1][0]

'MP'

In [ ]:
wap to create 3x3 array then slice it as we want 1,2 row and 1,2 column
after slicing check which element is divisibe by 3

In [62]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a1=a[1:3,1:3]

In [64]:
a1

array([[5, 6],
       [8, 9]])

In [65]:
a1[a1%3==0]

array([6, 9])

In [66]:
a1[a1%3==0].sum()

15

In [67]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [69]:
l=[]
for i in a:
    for j in i:
        l.append(j)
l
        

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [73]:
a=np.array([[[1,2,3,4,5,6,7,8,9,10]]])
a[0][0][0]

1

In [74]:
a1

array([[5, 6],
       [8, 9]])

In [75]:
b1=a1
b1

array([[5, 6],
       [8, 9]])

In [76]:
b1[1][1]=90
b1

array([[ 5,  6],
       [ 8, 90]])

In [2]:
import numpy as np

In [3]:
d=np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [4]:
d[1][1]=5
d

array([[1, 2],
       [3, 5]])

In [9]:
d[d>2]


array([3, 5])

In [10]:
d[1:2,1:2]

array([[5]])