In [3]:
import numpy as np

In [7]:
distance=np.array([10,20,30])
time=np.array([2,3,4])
sp=distance/time

In [8]:
sp

array([5.        , 6.66666667, 7.5       ])

In [6]:
type(sp)

numpy.ndarray

In [ ]:
axis 1    is for column  and axix o is for row

In [9]:
import numpy as np

In [10]:
l=[[1,2,3],[2,3,4],[3,4,5]]
arr=np.array(l)
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [12]:
arr[2][2]

5

In [13]:
arr.ndim

2

In [14]:
arr1=np.array([[[[[1,2,3]]]]])
arr1.ndim

5

In [15]:
arr.shape

(3, 3)

In [17]:
arr.shape[1]

3

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int32')

In [23]:
a=np.array([[1,2,3,4,]])
b=np.array([[5,6,7,8]])
a+b

array([[ 6,  8, 10, 12]])

In [25]:
a1=np.array([[1,2,3,4]])
a1*2

array([[2, 4, 6, 8]])